name: Run Tests
description: Action to run specified tests in a given directory

inputs:
  test-type:
    description: 'Type of tests to run (e.g., "api", "unit")'
    required: true
    type: string

  working-directory:
    description: 'Directory to run tests in'
    required: true
    type: string
    
runs:
  using: 'composite'
  steps:
    - name: Run ${{ inputs.test-type }} Tests
      run: npm run test:${{ inputs.test-type }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}