name: CI/CD Pipeline for Inventory Manager - Build, Test, Publish and Deploy Docker Images

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  provision-infra:
    uses: ./.github/workflows/provision-infra.yml

  build-images:
    uses: ./.github/workflows/build-images.yml
    
  test-backend:
    needs: build-images
    uses: ./.github/workflows/test-backend.yml
    secrets:
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

  test-frontend:
    needs: build-images
    uses: ./.github/workflows/test-frontend.yml
    secrets:
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

  publish-images:
    needs: 
      - test-backend
      - test-frontend
    if: (github.event_name != 'pull_request' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/publish-images.yml

  deploy:
    needs: publish-images
    if: (github.event_name != 'pull_request' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/deploy.yml