name: Provision Test Environment

on:
  workflow_call:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Setup backend
        uses: ./.github/actions/setup-node
        with:
          directory: backend

      - name: Setup frontend
        uses: ./.github/actions/setup-node
        with:
          directory: frontend

      - name: Build and Start application
        run: docker compose up --build -d