name: Test Backend

on:
  workflow_call:
    secrets:
      POSTGRES_USERNAME:
        required: true
      POSTGRES_PASSWORD:
        required: true
      JWT_SECRET_KEY:
        required: true

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - name: Setup backend
        uses: ./.github/actions/setup-node
        with:
          working-directory: backend

      - name: Load docker images from artifacts
        uses: actions/download-artifact@v6
        with:
          name: app-artifacts

      - name: Load application docker image
        run: |
          docker load -i backend.tar
          docker load -i frontend.tar
          docker image ls

      - name: Build and Start application
        run: docker compose up -d

      - name: Run backend unit tests
        uses: ./.github/actions/run-tests
        with:
          test-type: unit
          working-directory: backend

      - name: Run backend integration tests
        uses: ./.github/actions/run-tests
        with:
          test-type: api
          working-directory: backend
      
      - name: Stop application
        run: docker compose down --rmi all -v
        if: always()