name: Test Backend

on:
  workflow_call:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Run backend unit tests
        uses: ./.github/actions/run-tests
        with:
          test-type: unit
          directory: backend

      - name: Run backend integration tests
        uses: ./.github/actions/run-tests
        with:
          test-type: api
          directory: backend