name: Test Frontend

on:
  workflow_call:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - name: Setup frontend
        uses: ./.github/actions/setup-node
        with:
          working-directory: frontend

      - name: Load docker images from artifacts
        uses: actions/download-artifact@v6
        with:
          name: app-artifacts

      - name: Load application docker image
        run: |
          docker load -i backend.tar
          docker load -i frontend.tar
          docker image ls

      - name: Build and Start application
        run: docker compose up -d

      - name: Run frontend e2e tests
        uses: ./.github/actions/run-tests
        with:
          test-type: e2e
          working-directory: frontend

      - name: Stop application
        run: docker compose down --rmi all -v
        if: always()